#!/usr/bin/env bash
set -euo pipefail

git_status=$(git status --porcelain)

if [[ -n "$git_status" ]]; then
    echo "❌ Cannot build until there are no uncommitted changes"
    exit 1
fi

query_files=("highlights.scm" "injections.scm")

# Download the latest CSM files
for query_file in "${query_files[@]}"; do
    url="https://raw.githubusercontent.com/textwire/tree-sitter-textwire/refs/heads/master/queries/$query_file"
    dest="queries/$query_file"

    # Get the content of the file
    file_content=$(curl -s "$url")

    if [[ "$file_content" == *"404 Not Found"* ]]; then
        echo "❌ $url not found"
        exit 1
    fi

    # Update/create the destination file
    if [[ -n "$file_content" ]]; then
        echo "$file_content" > "$dest"
        echo "✅ Updated $dest"
    else
        echo "❌ Failed to download $url"
        exit 1
    fi
done
